export const GET_LIST_OF_FILMS = "GET_LIST_OF_FILMS";
export const GET_LIST_OF_FILMS_LOADING = "GET_LIST_OF_FILMS_LOADING";

export const ADD_FILM = "ADD_FILM";
export const ADD_FILM_WAITING = "ADD_FILM_WAITING";

export const DELETE_FILM = "DELETE_FILM";

export const SORT_LIST_OF_FILMS = "SORT_LIST_OF_FILMS";
export const SEARCH_IN_LIST_OF_FILMS = "SEARCH_IN_LIST_OF_FILMS";

export const SHOW_NEW_FILM_MODAL = "SHOW_NEW_FILM_MODAL";
export const HIDE_NEW_FILM_MODAL = "HIDE_NEW_FILM_MODAL";
